version : '3.8'
networks:
  isolation-network:
    driver: bridge
services :
  redis :
    container_name: auction_redis
    build:
      dockerfile: Dockerfile
      context: ./redis
    ports :
      - "6379:6379"
    networks :
      - isolation-network
  mongo :
    container_name : mongo
    image : mongo
    restart : always
    ports :
      - "27017:27017"
    # MONGO_INITDB_ROOT_USERNAME: root
    # MONGO_INITDB_ROOT_PASSWORD: secret
    volumes :
      - mongo-data:/data/db
    networks :
      - isolation-network
  mongo-express :
    image : mongo-express
    container_name : mongo-express
    restart : always
    ports :
      - "8081:8081"
    #    environment :
    #            ME_CONFIG_MONGODB_ADMINUSERNAME: root
    #            ME_CONFIG_MONGODB_ADMINPASSWORD: secret
    #            ME_CONFIG_BASICAUTH_USERNAME: admin
    #            ME_CONFIG_BASICAUTH_PASSWORD: secret
    networks :
      - isolation-network
volumes :
  mongo-data :